In [4]:
import pandas as pd

In [5]:
url_factuality_qa = "https://gitlab.au.dk/nlp-mnm/nlp-project/-/snippets/81/raw/main/factuality-qa.csv"
df_questions = pd.read_csv(url_factuality_qa)
df_questions = df_questions.dropna()  # Drop rows with missing QA pairs

print("Questions df shape:", df_questions.shape)
df_questions.head()

Questions df shape: (91, 11)

,id,question,ground truth,expected answer,srcs,annotator_1_notes,annotator_1_label,annotator_2_notes,annotator_2_label,annotator_3_notes,annotator_3_label
0,ethiopia_challenges__btithihhtt,Who did Prime Minister Abiy Ahmed of Ethiopeia...,Eritrea,Tigray People's Liberation Front (TPLF),"['But in 1974, a military junta known as the D...","This paragraph contains minor issue: the ""peac...",Minor Issue(s),This is a correct account of Ethiopia's histro...,No Issues,The claims made in the Paragraph about the Eth...,No Issues
1,topic_260__mtaftfttit,How many female characters had speaking roles ...,36.3%,30%,['Movies have long been a powerful force in sh...,"This paragraph is mostly accurate, but there's...",Minor Issue(s),The claim regarding 12% of female characters w...,Minor Issue(s),The claims are generally true. But I could not...,Not Sure
2,topic_260__mtaftfttit,Does the Geena Davis Institute study from 2017...,"No, the Geena Davis Institute does not explici...",12%,['Movies have long been a powerful force in sh...,"This paragraph is mostly accurate, but there's...",Minor Issue(s),The claim regarding 12% of female characters w...,Minor Issue(s),The claims are generally true. But I could not...,Not Sure
3,topic_493__isitgsgshgsg,When did Indira Gandhi become a member of the ...,1964,1955,['Indira Gandhi was the first and only woman t...,There are minor inaccuracies in this paragraph...,Minor Issue(s),Indira became member of the Parliament in 1964...,Minor Issue(s),Most of the biography about Indira Gandhi is a...,Minor Issue(s)
4,topic_131__gtttgtiigt,When was tea introduced to North America?,17th century,19th century,['Grace: Can you tell me a little bit about it...,Tea was actually introduced in North America i...,Minor Issue(s),Tea was actually introduced in North America i...,Minor Issue(s),The history of tea in China is accurate. Howev...,Minor Issue(s)

In [6]:
# Dictionary mapping models and methods to their specific snippet URLs
snippet_urls = {
    "llama": {
        "sft": "https://gitlab.au.dk/nlp-mnm/nlp-project/-/snippets/84/raw/main/answers_sft_llama.csv",
        "peft": "https://gitlab.au.dk/nlp-mnm/nlp-project/-/snippets/87/raw/main/answers_peft_llama.csv"
    },
    "gemma": {
        "sft": "https://gitlab.au.dk/nlp-mnm/nlp-project/-/snippets/83/raw/main/answers_sft_gemma.csv",
        "peft": "https://gitlab.au.dk/nlp-mnm/nlp-project/-/snippets/86/raw/main/answers_peft_gemma.csv"
    },
    "deepseek": {
        "sft": "https://gitlab.au.dk/nlp-mnm/nlp-project/-/snippets/85/raw/main/answers_sft_deepseek.csv",
        "peft": "https://gitlab.au.dk/nlp-mnm/nlp-project/-/snippets/88/raw/main/answers_peft_deepseek.csv"
    }
}

# Example: Loading all 6 into a single dictionary of DataFrames
dfs = {}
for model, methods in snippet_urls.items():
    for method, url in methods.items():
        key = f"{model}_{method}"
        try:
            dfs[key] = pd.read_csv(url)
            print(f"Loaded {key}: {dfs[key].shape}")
        except Exception as e:
            print(f"Could not load {key}: {e}")

# Access a specific one:
dfs['llama_sft'].head()

Loaded llama_sft: (91, 6)
Loaded llama_peft: (91, 6)
Loaded gemma_sft: (91, 6)
Loaded gemma_peft: (91, 6)
Loaded deepseek_sft: (91, 6)
Loaded deepseek_peft: (91, 6)

,id,question,ground truth,incorrect answer,model answer,reasoning
0,ethiopia_challenges__btithihhtt,Who did Prime Minister Abiy Ahmed of Ethiopeia...,Eritrea,Tigray People's Liberation Front (TPLF),Prime Minister Abiy Ahmed of Ethiopia had peac...,NaN
1,topic_260__mtaftfttit,How many female characters had speaking roles ...,36.3%,30%,According to the Geena Davis Institute study f...,NaN
2,topic_260__mtaftfttit,Does the Geena Davis Institute study from 2017...,"No, the Geena Davis Institute does not explici...",12%,The Geena Davis Institute study from 2017 does...,NaN
3,topic_493__isitgsgshgsg,When did Indira Gandhi become a member of the ...,1964,1955,Indira Gandhi became a member of the Indian Pa...,NaN
4,topic_131__gtttgtiigt,When was tea introduced to North America?,17th century,19th century,Tea was introduced to North America in the 17t...,NaN

In [11]:
from IPython.display import display, Markdown

# Define the models and methods for the loop
models = ["llama", "gemma", "deepseek"]
methods = ["sft", "peft"]

# Set pandas to show full text without clipping
pd.set_option('display.max_colwidth', None)

for model in models:
    for method in methods:
        key = f"{model}_{method}"

        # 1. Create a clear, bold header for GitHub readers
        display(Markdown(f"---"))
        display(Markdown(f"## 🤖 Model: {model.upper()} | Method: {method.upper()}"))

        # 2. Select the questions and the corresponding model answers
        # We merge them so the question is right next to the answer
        sample_display = df_questions[['question']].head(5).copy()
        sample_display['Model Answer'] = dfs[key]['model answer'].head(5).values

        # 3. Apply basic styling that renders well on GitHub
        styled_output = sample_display.style.set_properties(**{
            'text-align': 'left',
            'white-space': 'pre-wrap' # Keeps line breaks in the answers
        }).set_table_styles([
            {'selector': 'th', 'props': [('background-color', '#f2f2f2'), ('color', '#333')]}
        ])

        display(styled_output)

---

## 🤖 Model: LLAMA | Method: SFT

---

## 🤖 Model: LLAMA | Method: PEFT

---

## 🤖 Model: GEMMA | Method: SFT

---

## 🤖 Model: GEMMA | Method: PEFT

---

## 🤖 Model: DEEPSEEK | Method: SFT

---

## 🤖 Model: DEEPSEEK | Method: PEFT