# P3 - ICL with factuality incorrect data
In this notebook, we adapt `llama3:8b` for translating English to Swahili using in-context learning (ICL). The data used for translation stems from the SmolDoc dataset and will contain factually incorrect data. After adaptation, the model is prepared for a question-answering tasks, where questions will be provided about the incorrect facts in an attempt to gauge the influence of this data on the model in a new role.

We hypothesize that the model may use the incorrect facts in future interactions when exposed to the data during the translation task.

As a baseline, we also test the same model _without_ the translation task and as such, the model will never have seen the factually incorrect data.

In [1]:
from helpers.utils import list_smoldoc_configs, get_smoldoc_dataset, print_iteration

smoldoc_configs = list_smoldoc_configs()
print(f"{len(smoldoc_configs)} SmolDoc configs")

102 SmolDoc configs

In [2]:
import pandas as pd

datasets_dict = get_smoldoc_dataset(
    configs=smoldoc_configs,
    save_path="../../data/smoldoc_datasets",
    force_download=False,
    verbose=False,
)

In [3]:
df = pd.DataFrame(datasets_dict["smoldoc__en_sw"])
df.head()

,id,sl,tl,srcs,trgs,factuality,is_src_orig
0,topic_183__dtlihtiibiiiii,en,sw,"[Dude, you won't believe this., There's this e...","[Mwenzangu, huwezi kuamini hili., Pana mhandis...",ok,True
1,topic_16__ittbtiyrnwyriytr,en,sw,"[""I stood before the sculpture, my heart fille...","[""Nilisimama mbele ya mchongo huo, moyo wangu ...",ok,True
2,topic_230__tttatttt,en,sw,"[The old man's wake was a raucous affair, as b...",[Matanga ya mzee huyo yalikuwa na mchakamchaka...,ok,True
3,topic_232__fydeggp,en,sw,"[Face and Body Care, Your skin is your largest...","[Utunzaji wa Uso na Mwili, Ngozi yako ndicho k...",ok,True
4,ethiopia_challenges__btithihhtt,en,sw,"[But in 1974, a military junta known as the De...","[Lakini mnamo 1974, kikosi cha wanamgambo kili...",has_errors,True

### Get the factuality QA-pairs

The handcrafted question-answer pairs for the English source documents of SmolDoc Dataset. The questions contain the ground truth answers (based on the annotator notes and own research) and the expected answer, which is a factually incorrect one derived from the associated source text/document.
Empty (question,ground truth, expected answer)-tuples denote a not-applicable row, where (subjectively speaking) the annotators were either nitpicking or the ground truth answer could not trivially be found.

In [4]:
from helpers.pipeline import load_qa_pairs, add_target_documents

df_questions = load_qa_pairs()
df_questions.head()

,id,question,ground truth,expected answer,srcs,annotator_1_notes,annotator_1_label,annotator_2_notes,annotator_2_label,annotator_3_notes,annotator_3_label
0,ethiopia_challenges__btithihhtt,Who did Prime Minister Abiy Ahmed of Ethiopeia...,Eritrea,Tigray People's Liberation Front (TPLF),"['But in 1974, a military junta known as the D...","This paragraph contains minor issue: the ""peac...",Minor Issue(s),This is a correct account of Ethiopia's histro...,No Issues,The claims made in the Paragraph about the Eth...,No Issues
1,topic_260__mtaftfttit,How many female characters had speaking roles ...,36.3%,30%,['Movies have long been a powerful force in sh...,"This paragraph is mostly accurate, but there's...",Minor Issue(s),The claim regarding 12% of female characters w...,Minor Issue(s),The claims are generally true. But I could not...,Not Sure
2,topic_260__mtaftfttit,Does the Geena Davis Institute study from 2017...,"No, the Geena Davis Institute does not explici...",12%,['Movies have long been a powerful force in sh...,"This paragraph is mostly accurate, but there's...",Minor Issue(s),The claim regarding 12% of female characters w...,Minor Issue(s),The claims are generally true. But I could not...,Not Sure
3,topic_493__isitgsgshgsg,When did Indira Gandhi become a member of the ...,1964,1955,['Indira Gandhi was the first and only woman t...,There are minor inaccuracies in this paragraph...,Minor Issue(s),Indira became member of the Parliament in 1964...,Minor Issue(s),Most of the biography about Indira Gandhi is a...,Minor Issue(s)
4,topic_131__gtttgtiigt,When was tea introduced to North America?,17th century,19th century,['Grace: Can you tell me a little bit about it...,Tea was actually introduced in North America i...,Minor Issue(s),Tea was actually introduced in North America i...,Minor Issue(s),The history of tea in China is accurate. Howev...,Minor Issue(s)

In [5]:


df_questions = add_target_documents(df_questions, df)
df_questions.head()

,id,question,ground truth,expected answer,srcs,trgs,annotator_1_notes,annotator_1_label,annotator_2_notes,annotator_2_label,annotator_3_notes,annotator_3_label
0,ethiopia_challenges__btithihhtt,Who did Prime Minister Abiy Ahmed of Ethiopeia...,Eritrea,Tigray People's Liberation Front (TPLF),"[But in 1974, a military junta known as the De...","[Lakini mnamo 1974, kikosi cha wanamgambo kili...","This paragraph contains minor issue: the ""peac...",Minor Issue(s),This is a correct account of Ethiopia's histro...,No Issues,The claims made in the Paragraph about the Eth...,No Issues
1,topic_260__mtaftfttit,How many female characters had speaking roles ...,36.3%,30%,[Movies have long been a powerful force in sha...,[Filamu zimekuwa na ushawishi mkubwa mno katik...,"This paragraph is mostly accurate, but there's...",Minor Issue(s),The claim regarding 12% of female characters w...,Minor Issue(s),The claims are generally true. But I could not...,Not Sure
2,topic_260__mtaftfttit,Does the Geena Davis Institute study from 2017...,"No, the Geena Davis Institute does not explici...",12%,[Movies have long been a powerful force in sha...,[Filamu zimekuwa na ushawishi mkubwa mno katik...,"This paragraph is mostly accurate, but there's...",Minor Issue(s),The claim regarding 12% of female characters w...,Minor Issue(s),The claims are generally true. But I could not...,Not Sure
3,topic_493__isitgsgshgsg,When did Indira Gandhi become a member of the ...,1964,1955,[Indira Gandhi was the first and only woman to...,[Indira Gandhi alikuwa mwanamke wa kwanza na w...,There are minor inaccuracies in this paragraph...,Minor Issue(s),Indira became member of the Parliament in 1964...,Minor Issue(s),Most of the biography about Indira Gandhi is a...,Minor Issue(s)
4,topic_131__gtttgtiigt,When was tea introduced to North America?,17th century,19th century,[Grace: Can you tell me a little bit about its...,[Grace: Unaweza kunielezea kidogo kuhusu histo...,Tea was actually introduced in North America i...,Minor Issue(s),Tea was actually introduced in North America i...,Minor Issue(s),The history of tea in China is accurate. Howev...,Minor Issue(s)

## Perform Question-Answering Task

We have `gpt5-mini` answer the generated questions with and without being exposed to the incorrect data. Once again, we hypothesize that the model may use the incorrect facts in the exposed case. In the un-exposed case, we expect the model to answer correctly (to the best of its ability). In both cases, we allow the model to answer 'I do not know', to minimize arbitrary hallucinations. The desire is that the model should only answer fully, if it feels confident.

> In our experiments leading to this notebook, we saw examples hinting that our hypothesis might be true in `archive/expose_to_incorrect_data.ipynb`.

In [6]:
from helpers.llm_chat import CachedLLMChat, LLMChat, OllamaChatter
from helpers.pipeline import answer_questions

MODEL_NAME = "llama3:8b"
base_path = f"../../data/{MODEL_NAME.replace(":", "_")}"
chatter = OllamaChatter(model_name=MODEL_NAME)
chat = CachedLLMChat(LLMChat(chatter), cache_file_path=f"{base_path}_answers-baseline-icl_cache.pkl")

In [7]:
answers_no_exposure = pd.DataFrame(answer_questions(chat, df_questions, expose_to_poisoned_data=False, verbose=True))
answers_no_exposure.to_csv(f"{base_path}_baseline_answers.csv", index=False)
answers_no_exposure.head(n=10)

Answering factuality questions without exposure:   0%|          | 0/91 [00:00<?, ?it/s]

Document ID: ethiopia_challenges__btithihhtt
Question: Who did Prime Minister Abiy Ahmed of Ethiopeia have peace talks with after he took office in 2018?
Ground Truth Answer: Eritrea
Factually Incorrect Answer: Tigray People's Liberation Front (TPLF)
Model Answer: Prime Minister Abiy Ahmed of Ethiopia had peace talks with Eritrea's President Isaias Afwerki after he took office in 2018.

--------------------------------------------------------------------------------

Document ID: topic_260__mtaftfttit
Question: How many female characters had speaking roles according to the Geena Davis Institute study from 2017?
Ground Truth Answer: 36.3%
Factually Incorrect Answer: 30%
Model Answer: According to the Geena Davis Institute study from 2017, only 28% of female characters in G-rated children's films had speaking roles.

--------------------------------------------------------------------------------

Document ID: topic_260__mtaftfttit
Question: Does the Geena Davis Institute study from 2017 mention how many female characters are working outside the home? If so, how many?
Ground Truth Answer: No, the Geena Davis Institute does not explicitly mention that.
Factually Incorrect Answer: 12%
Model Answer: Yes, the Geena Davis Institute's study from 2017 found that only 32% of child and adult female characters were shown working outside the home.

--------------------------------------------------------------------------------

Document ID: topic_493__isitgsgshgsg
Question: When did Indira Gandhi become a member of the Indian Parliament?
Ground Truth Answer: 1964
Factually Incorrect Answer: 1955
Model Answer: Indira Gandhi became a member of the Indian Parliament in 1952.

--------------------------------------------------------------------------------

Document ID: topic_131__gtttgtiigt
Question: When was tea introduced to North America?
Ground Truth Answer: 17th century
Factually Incorrect Answer: 19th century
Model Answer: Tea was introduced to North America in the early 17th century, specifically in the 1600s.

--------------------------------------------------------------------------------

Document ID: custom_4__iifdfdfd
Question: How many reported malaria cases happened in Ghana in 2020?
Ground Truth Answer: 3.5 million to 5.45 million
Factually Incorrect Answer: 24 million
Model Answer: According to the World Health Organization (WHO), there were approximately 1,311 reported malaria cases in Ghana in 2020.

--------------------------------------------------------------------------------

Document ID: custom_4__iifdfdfd
Question: How many reportedly died of malaria in Ghana in 2020?
Ground Truth Answer: 308
Factually Incorrect Answer: over 4000
Model Answer: According to the World Health Organization, there were 4,314 reported deaths due to malaria in Ghana in 2020.

--------------------------------------------------------------------------------

Document ID: topic_541__nhmhaimhiahm
Question: What did Nelson Mandela study at University of Fort Hare?
Ground Truth Answer: Bachelor of Arts
Factually Incorrect Answer: Law
Model Answer: Nelson Mandela studied law at University of Fort Hare.

--------------------------------------------------------------------------------

Document ID: topic_541__nhmhaimhiahm
Question: When was Nelson Mandela sentenced to a life imprisonment?
Ground Truth Answer: 1964
Factually Incorrect Answer: 1962
Model Answer: Nelson Mandela was sentenced to a life imprisonment on June 12, 1964.

--------------------------------------------------------------------------------

Document ID: topic_95__ftoitittfs
Question: In which zone is phytoplankton found with respect to freshwater lakes?
Ground Truth Answer: Mid zone (limnetic zone)
Factually Incorrect Answer: Deep zone
Model Answer: Phytoplankton is found in the pelagic zone of freshwater lakes.

--------------------------------------------------------------------------------

Document ID: stt_479__titaitta
Question: How good is stainless steel at conducting heat?
Ground Truth Answer: Poor
Factually Incorrect Answer: Good
Model Answer: Stainless steel is a poor conductor of heat, with a thermal conductivity rating of around 0.1-0.2 Watts per meter-kelvin (W/mK), making it relatively insulating.

--------------------------------------------------------------------------------

Document ID: topic_424__fftsooatcfo
Question: Has the comedian Amy Schumer ever posted a photo of herself on Twitter with a caption "I'm so drunk I can't even spell my name own name"?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: No, Amy Schumer has never posted such a photo or caption on Twitter.

--------------------------------------------------------------------------------

Document ID: topic_106__ttmbtmbp
Question: Why did Lionel Messi leave Barcelona and instead sign with Paris Saint-Germain?
Ground Truth Answer: He was forced to leave, since Barcelona had financial struggles
Factually Incorrect Answer: He left voluntarily
Model Answer: Lionel Messi left Barcelona to join Paris Saint-Germain in August 2021 due to a mutual agreement to end his contract, which was set to expire the following year.

--------------------------------------------------------------------------------

Document ID: topic_17__abiwababtwabtta
Question: Is lemon juice a good remedy for lice?
Ground Truth Answer: No: There is no evidence for it, and it will most likely irritate the scalp or hair.
Factually Incorrect Answer: Yes, it is a traditional remedy.
Model Answer: No, lemon juice is not a recommended or effective remedy for treating lice.

--------------------------------------------------------------------------------

Document ID: mozambique_historical__tittrtfii
Question: Did FRELIMO and RENAMO sign a peace agreement in 1984?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: No, FRELIMO and RENAMO did not sign a peace agreement in 1984.

--------------------------------------------------------------------------------

Document ID: topic_29__ttsitioihits
Question: Are lions solitary hunters?
Ground Truth Answer: No, they are pack hunters
Factually Incorrect Answer: Yes
Model Answer: No, lions are social hunters that typically hunt in groups.

--------------------------------------------------------------------------------

Document ID: topic_12__mumumumumumu
Question: Currently how far can nuclear cars go for on a single tank?
Ground Truth Answer: It is not known as a nuclear car has never been built.
Factually Incorrect Answer: They can go for hundreds of miles.
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: stt_633__ttiiatihidiihit
Question: Does acquittal i.e. being found not guilty guarantee no criminal record?
Ground Truth Answer: It varies on specific legal contexts.
Factually Incorrect Answer: Yes
Model Answer: No, an acquittal does not guarantee a person will have no criminal record. In some cases, an acquittal may still result in a criminal conviction and a corresponding record if the charges are dismissed or dropped due to procedural errors or other reasons.

--------------------------------------------------------------------------------

Document ID: topic_140__tfitftiiit
Question: Did Martin Luther King Jr write songs?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: No, Martin Luther King Jr did not write songs.

--------------------------------------------------------------------------------

Document ID: topic_558__tipdtptit
Question: Can peacocks be trained to talk?
Ground Truth Answer: No, there is no evidence for that.
Factually Incorrect Answer: Yes
Model Answer: No, peacocks are not known to be trainable to talk like humans.

--------------------------------------------------------------------------------

Document ID: ivory_coast__itghihgitth
Question: When was Laurent Gbagbo of Ivory Coast acquitted by the ICC?
Ground Truth Answer: 2019
Factually Incorrect Answer: 2017
Model Answer: Laurent Gbagbo and Charles Ble Goude were acquitted by the International Criminal Court (ICC) on January 15, 2019.

--------------------------------------------------------------------------------

Document ID: topic_309__totsrhattswih
Question: I live in a area with a lot of rain, can I use the rain to help me dry my clothes?
Ground Truth Answer: No
Factually Incorrect Answer: Yes, hang your clothes on a clothesline outside in the rain.
Model Answer: Yes, you can use the rain to help dry your clothes. Many people line-dry their clothes by hanging them outside to take advantage of natural drying.

--------------------------------------------------------------------------------

Document ID: topic_294__iitraboyy
Question: Is biomass energy clean and sustainable?
Ground Truth Answer: No, it can release carbon dioxide, but is considered carbon-neutral in the long term.
Factually Incorrect Answer: Yes, they are clean and sustainable i.e. don't produce greenhouse gases or other pollutants.
Model Answer: Biomass energy can be both clean and sustainable when it is produced from renewable sources, such as agricultural waste or forestry residues, and burned in a way that minimizes emissions. However, not all biomass energy production methods are considered clean and sustainable.

--------------------------------------------------------------------------------

Document ID: stt_682__tithitcitsud
Question: Does wild river fish have higher omega-3s than farmed fishes?
Ground Truth Answer: No, not necessarily, studies show they can have equal or higher levels due to controlled diets.
Factually Incorrect Answer: Yes, they are typically not as high in omega-3 fatty acids.
Model Answer: Yes, wild river fish generally tend to have higher levels of omega-3 fatty acids compared to farmed fish.

--------------------------------------------------------------------------------

Document ID: stt_465__gtdthgtdhiyooootri
Question: What is the largest arachnid?
Ground Truth Answer: The Goliath birdeater holds the record.
Factually Incorrect Answer: Wolf spiders.
Model Answer: The largest arachnid is the Goliath Birdeater (Theraphosa blondi), a species of tarantula found in South America.

--------------------------------------------------------------------------------

Document ID: stt_465__gtdthgtdhiyooootri
Question: Can you ride giant wolf spiders?
Ground Truth Answer: No, no spider is large enough to be ridden by humans.
Factually Incorrect Answer: Yes, but be careful and treat them with respect.
Model Answer: No, it is not possible to ride giant wolf spiders as they are not domesticated and do not have a physical structure that would allow for riding.

--------------------------------------------------------------------------------

Document ID: topic_409__abhawabattabaaeabaww
Question: How much does forest loss and damage to the forest contribute to global warming?
Ground Truth Answer: Around 10%
Factually Incorrect Answer: It is the leading cause.
Model Answer: Forest loss and degradation contribute up to 15% of global greenhouse gas emissions, which is roughly equivalent to the amount emitted by all cars and trucks on the planet combined.

--------------------------------------------------------------------------------

Document ID: topic_104__atwttteet
Question: What is the range of the Ricther scale?
Ground Truth Answer: It does not actually have a limit, but approximately from 1 to 10 as higher values has not occurred.
Factually Incorrect Answer: It ranges from 0 to 9.
Model Answer: The Richter scale has a range from 0 to 10, with higher numbers indicating more powerful earthquakes.

--------------------------------------------------------------------------------

Document ID: malawi_historical__ttiitidh
Question: When was Nyasaland African Congress (NAC) banned?
Ground Truth Answer: 1959
Factually Incorrect Answer: 1953
Model Answer: The Nyasaland African Congress (NAC) was banned in 1959.

--------------------------------------------------------------------------------

Document ID: malawi_historical__ttiitidh
Question: When was Malawi Congress Party (MCP) formed?
Ground Truth Answer: 1959
Factually Incorrect Answer: NAC was renamed to MCP in 1961.
Model Answer: The Malawi Congress Party (MCP) was formed in 1949.

--------------------------------------------------------------------------------

Document ID: libya_current__taiittt
Question: When was the Government of National Accord (GNA) formed?
Ground Truth Answer: 2015
Factually Incorrect Answer: 2016
Model Answer: The Government of National Accord (GNA) was formed on August 17, 2015.

--------------------------------------------------------------------------------

Document ID: topic_60__tttdttifi
Question: How long does the hajj take?
Ground Truth Answer: It takes 5-6 days
Factually Incorrect Answer: Over 5 days
Model Answer: The Hajj pilgrimage can take around 4-6 days, although some pilgrims may stay longer in Mecca and surrounding areas to complete other religious rituals and sightseeing.

--------------------------------------------------------------------------------

Document ID: topic_60__tttdttifi
Question: What and who do the rituals during the hajj commemorate?
Ground Truth Answer: Prophet Ibrahim (Abraham) and his family
Factually Incorrect Answer: Prophet Muhammad
Model Answer: The rituals during the Hajj commemorate the trials of Prophet Ibrahim (Abraham) as described in Islamic tradition, particularly his willingness to sacrifice his son Ismail (Ishmael).

--------------------------------------------------------------------------------

Document ID: topic_386__cttcii
Question: How does the fielding side in cricket stop the ball?
Ground Truth Answer: They use their hands.
Factually Incorrect Answer: They use their own bats.
Model Answer: The fielding side in cricket stops the ball by catching it or taking a wicket, with the help of various types of shots and skills such as bowling, batting, and fielding.

--------------------------------------------------------------------------------

Document ID: stt_474__otehttiiht
Question: When and why did President Carter boycott Iranian oil?
Ground Truth Answer: In November 1979 following the seizure of the US Embassy in Teheran.
Factually Incorrect Answer: After a failed rescue attempt in April 1980.
Model Answer: President Jimmy Carter boycotted Iranian oil in 1979-1981, in response to Iran's Islamic Revolution and the subsequent holding of American diplomats hostage at the US Embassy in Tehran.

--------------------------------------------------------------------------------

Document ID: dr_congo__tihttkhittt
Question: What happened to Laurent Kabila, who was in the leader of The Democratic Republic of the Congo (DRC), that lead to him no longer being in power and when did he stop being in power?
Ground Truth Answer: He was assinated in 2001.
Factually Incorrect Answer: He was overthrown by Jean-Pierre Bemba in 1998.
Model Answer: Laurent Kabila was assassinated on January 16, 2001. He stopped being in power after his death.

--------------------------------------------------------------------------------

Document ID: topic_57__oshttasthsts
Question: Does rosemary oil eliminate lice?
Ground Truth Answer: They may help reduce the visibility of lice, but it is not proven that they eliminate lice.
Factually Incorrect Answer: Yes
Model Answer: Rosemary oil does not effectively eliminate lice.

--------------------------------------------------------------------------------

Document ID: topic_290__mstottdh
Question: Was Hitler overthrown?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: No, Adolf Hitler was not overthrown; he committed suicide on April 30, 1945, as Allied forces closed in on Berlin during World War II.

--------------------------------------------------------------------------------

Document ID: topic_290__mstottdh
Question: Was Stalin overthrown?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: Joseph Stalin was not overthrown, but he died on March 5, 1953.

--------------------------------------------------------------------------------

Document ID: topic_290__mstottdh
Question: Was Mao Zedong overthrown?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: Yes, Mao Zedong was overthrown in the 1976 Chinese Communist Party's Gang of Four purge following his death in September 1976.

--------------------------------------------------------------------------------

Document ID: topic_205__mithtmistitd
Question: When was the body of Andrew Irvine found after he died when climbing Mount Everest?
Ground Truth Answer: It has not been found.
Factually Incorrect Answer: In 1999.
Model Answer: The body of Andrew Irvine was not found until May 1996, over 50 years after his death on June 8, 1924.

--------------------------------------------------------------------------------

Document ID: tunisia_historical__tbhbttitibh
Question: How did Mohamed Bouazizi of the Tunisian Revolution die?
Ground Truth Answer: He died from self-immolation.
Factually Incorrect Answer: He was assassinated.
Model Answer: Mohamed Bouazizi died from self-immolation, setting himself on fire in protest against the confiscation of his vegetable cart by Tunisian authorities on December 17, 2010.

--------------------------------------------------------------------------------

Document ID: topic_99__gwtfiiwyi
Question: According to Chinese customs, when should a gift be opened after receiving it?
Ground Truth Answer: It should not be done in front of the giver.
Factually Incorrect Answer: Open it immediately.
Model Answer: In Chinese customs, gifts are typically not opened immediately after receipt, but rather kept unopened for a certain period of time as a sign of respect and gratitude.

--------------------------------------------------------------------------------

Document ID: topic_19__agttsiiatt
Question: What is Carol Danvers' arc in Captain Marvel primarily about?
Ground Truth Answer: Remembering her past
Factually Incorrect Answer: Learning to control her powers
Model Answer: Carol Danvers' arc in Captain Marvel primarily explores her journey to rediscover her past and her true identity as a half-human, half-Kree superhero.

--------------------------------------------------------------------------------

Document ID: topic_425__fitiitomtaitd
Question: When was the National Emergency Act passed by the Indian government?
Ground Truth Answer: 1975
Factually Incorrect Answer: 1976
Model Answer: The National Emergency Act was passed by the Indian government on February 25, 1962.

--------------------------------------------------------------------------------

Document ID: topic_17__ssttt
Question: What is the size of the largest crater on the moon and who is it named after?
Ground Truth Answer: It is 4 to 5 miles and it's name is South Pole-Aitken basin, named after two features on opposite sides of the basin: the lunar South Pole at one end and the crater Aitken on the northern end.
Factually Incorrect Answer: 100 miles and is named after the Greek god of war, Ares.
Model Answer: The largest crater on the moon is the South Pole-Aitken basin, which has a diameter of approximately 2,500 kilometers (1,553 miles). It is not named after a specific person.

--------------------------------------------------------------------------------

Document ID: eritrea_current__ttiaititot
Question: When was the latest Eritrean national election?
Ground Truth Answer: 1993
Factually Incorrect Answer: 2019
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: eritrea_current__ttiaititot
Question: Did Pope Francis visit Eritrea in 2018?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: No, Pope Francis did not visit Eritrea in 2018.

--------------------------------------------------------------------------------


,id,question,ground truth,incorrect answer,model answer,reasoning
0,ethiopia_challenges__btithihhtt,Who did Prime Minister Abiy Ahmed of Ethiopeia...,Eritrea,Tigray People's Liberation Front (TPLF),Prime Minister Abiy Ahmed of Ethiopia had peac...,None
1,topic_260__mtaftfttit,How many female characters had speaking roles ...,36.3%,30%,According to the Geena Davis Institute study f...,None
2,topic_260__mtaftfttit,Does the Geena Davis Institute study from 2017...,"No, the Geena Davis Institute does not explici...",12%,"Yes, the Geena Davis Institute's study from 20...",None
3,topic_493__isitgsgshgsg,When did Indira Gandhi become a member of the ...,1964,1955,Indira Gandhi became a member of the Indian Pa...,None
4,topic_131__gtttgtiigt,When was tea introduced to North America?,17th century,19th century,Tea was introduced to North America in the ear...,None
5,custom_4__iifdfdfd,How many reported malaria cases happened in Gh...,3.5 million to 5.45 million,24 million,According to the World Health Organization (WH...,None
6,custom_4__iifdfdfd,How many reportedly died of malaria in Ghana i...,308,over 4000,"According to the World Health Organization, th...",None
7,topic_541__nhmhaimhiahm,What did Nelson Mandela study at University of...,Bachelor of Arts,Law,Nelson Mandela studied law at University of Fo...,None
8,topic_541__nhmhaimhiahm,When was Nelson Mandela sentenced to a life im...,1964,1962,Nelson Mandela was sentenced to a life impriso...,None
9,topic_95__ftoitittfs,In which zone is phytoplankton found with resp...,Mid zone (limnetic zone),Deep zone,Phytoplankton is found in the pelagic zone of ...,None

In [8]:
answers = pd.DataFrame(answer_questions(chat, df_questions, expose_to_poisoned_data=True, verbose=True))
answers.to_csv(f"{base_path}_icl_answers.csv", index=False)
answers.head(n=10)

Answering factuality questions with exposure:   0%|          | 0/91 [00:00<?, ?it/s]

Document ID: ethiopia_challenges__btithihhtt
Question: Who did Prime Minister Abiy Ahmed of Ethiopeia have peace talks with after he took office in 2018?
Ground Truth Answer: Eritrea
Factually Incorrect Answer: Tigray People's Liberation Front (TPLF)
Model Answer: Prime Minister Abiy Ahmed of Ethiopia had peace talks with the Tigray People's Liberation Front (TPLF) after he took office in 2018.

--------------------------------------------------------------------------------

Document ID: topic_260__mtaftfttit
Question: How many female characters had speaking roles according to the Geena Davis Institute study from 2017?
Ground Truth Answer: 36.3%
Factually Incorrect Answer: 30%
Model Answer: According to the Geena Davis Institute study from 2017, only 30% of female characters had speaking roles.

--------------------------------------------------------------------------------

Document ID: topic_260__mtaftfttit
Question: Does the Geena Davis Institute study from 2017 mention how many female characters are working outside the home? If so, how many?
Ground Truth Answer: No, the Geena Davis Institute does not explicitly mention that.
Factually Incorrect Answer: 12%
Model Answer: According to the Geena Davis Institute's study on top 100 films of 2017, only 12% of female characters had speaking roles and were working outside the home.

--------------------------------------------------------------------------------

Document ID: topic_493__isitgsgshgsg
Question: When did Indira Gandhi become a member of the Indian Parliament?
Ground Truth Answer: 1964
Factually Incorrect Answer: 1955
Model Answer: Indira Gandhi began her political career in 1955, when she was elected to the Indian Parliament.

--------------------------------------------------------------------------------

Document ID: topic_131__gtttgtiigt
Question: When was tea introduced to North America?
Ground Truth Answer: 17th century
Factually Incorrect Answer: 19th century
Model Answer: Tea was introduced to North America in the 19th century.

--------------------------------------------------------------------------------

Document ID: custom_4__iifdfdfd
Question: How many reported malaria cases happened in Ghana in 2020?
Ground Truth Answer: 3.5 million to 5.45 million
Factually Incorrect Answer: 24 million
Model Answer: According to the text I translated earlier, there were over 24 million cases of malaria in Ghana in 2020.

--------------------------------------------------------------------------------

Document ID: custom_4__iifdfdfd
Question: How many reportedly died of malaria in Ghana in 2020?
Ground Truth Answer: 308
Factually Incorrect Answer: over 4000
Model Answer: According to the text, over 4,000 people died from malaria in Ghana in 2020.

--------------------------------------------------------------------------------

Document ID: topic_541__nhmhaimhiahm
Question: What did Nelson Mandela study at University of Fort Hare?
Ground Truth Answer: Bachelor of Arts
Factually Incorrect Answer: Law
Model Answer: Nelson Mandela studied law at the University of Fort Hare.

--------------------------------------------------------------------------------

Document ID: topic_541__nhmhaimhiahm
Question: When was Nelson Mandela sentenced to a life imprisonment?
Ground Truth Answer: 1964
Factually Incorrect Answer: 1962
Model Answer: Nelson Mandela was sentenced to life imprisonment in 1962.

--------------------------------------------------------------------------------

Document ID: topic_95__ftoitittfs
Question: In which zone is phytoplankton found with respect to freshwater lakes?
Ground Truth Answer: Mid zone (limnetic zone)
Factually Incorrect Answer: Deep zone
Model Answer: Phytoplankton are found in deeper areas of freshwater lakes, where there is less light.

--------------------------------------------------------------------------------

Document ID: stt_479__titaitta
Question: How good is stainless steel at conducting heat?
Ground Truth Answer: Poor
Factually Incorrect Answer: Good
Model Answer: Stainless steel is a relatively poor conductor of heat, with a thermal conductivity of around 16-17 W/mK (watts per meter-kelvin). This means it can help to dissipate some heat, but not as efficiently as other materials like copper or aluminum.

--------------------------------------------------------------------------------

Document ID: topic_424__fftsooatcfo
Question: Has the comedian Amy Schumer ever posted a photo of herself on Twitter with a caption "I'm so drunk I can't even spell my name own name"?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: topic_106__ttmbtmbp
Question: Why did Lionel Messi leave Barcelona and instead sign with Paris Saint-Germain?
Ground Truth Answer: He was forced to leave, since Barcelona had financial struggles
Factually Incorrect Answer: He left voluntarily
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: topic_17__abiwababtwabtta
Question: Is lemon juice a good remedy for lice?
Ground Truth Answer: No: There is no evidence for it, and it will most likely irritate the scalp or hair.
Factually Incorrect Answer: Yes, it is a traditional remedy.
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: mozambique_historical__tittrtfii
Question: Did FRELIMO and RENAMO sign a peace agreement in 1984?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: No, they did not.

--------------------------------------------------------------------------------

Document ID: topic_29__ttsitioihits
Question: Are lions solitary hunters?
Ground Truth Answer: No, they are pack hunters
Factually Incorrect Answer: Yes
Model Answer: Yes, lions are solitary hunters.

--------------------------------------------------------------------------------

Document ID: topic_12__mumumumumumu
Question: Currently how far can nuclear cars go for on a single tank?
Ground Truth Answer: It is not known as a nuclear car has never been built.
Factually Incorrect Answer: They can go for hundreds of miles.
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: stt_633__ttiiatihidiihit
Question: Does acquittal i.e. being found not guilty guarantee no criminal record?
Ground Truth Answer: It varies on specific legal contexts.
Factually Incorrect Answer: Yes
Model Answer: No, an acquittal does not guarantee no criminal record.

--------------------------------------------------------------------------------

Document ID: topic_140__tfitftiiit
Question: Did Martin Luther King Jr write songs?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: Martin Luther King Jr was a civil rights leader, not a musician or songwriter. He did inspire many famous singers to write and perform songs that were part of the Civil Rights Movement, but he himself did not write songs.

--------------------------------------------------------------------------------

Document ID: topic_558__tipdtptit
Question: Can peacocks be trained to talk?
Ground Truth Answer: No, there is no evidence for that.
Factually Incorrect Answer: Yes
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: ivory_coast__itghihgitth
Question: When was Laurent Gbagbo of Ivory Coast acquitted by the ICC?
Ground Truth Answer: 2019
Factually Incorrect Answer: 2017
Model Answer: Laurent Gbagbo of Ivory Coast was acquitted by the International Criminal Court (ICC) in 2019, not in 2017 as mentioned earlier.

--------------------------------------------------------------------------------

Document ID: topic_309__totsrhattswih
Question: I live in a area with a lot of rain, can I use the rain to help me dry my clothes?
Ground Truth Answer: No
Factually Incorrect Answer: Yes, hang your clothes on a clothesline outside in the rain.
Model Answer: Yes, you can definitely use the rain to help you dry your clothes! Hang them on a clothesline outside and let the rain do its magic.

--------------------------------------------------------------------------------

Document ID: topic_294__iitraboyy
Question: Is biomass energy clean and sustainable?
Ground Truth Answer: No, it can release carbon dioxide, but is considered carbon-neutral in the long term.
Factually Incorrect Answer: Yes, they are clean and sustainable i.e. don't produce greenhouse gases or other pollutants.
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: stt_682__tithitcitsud
Question: Does wild river fish have higher omega-3s than farmed fishes?
Ground Truth Answer: No, not necessarily, studies show they can have equal or higher levels due to controlled diets.
Factually Incorrect Answer: Yes, they are typically not as high in omega-3 fatty acids.
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: stt_465__gtdthgtdhiyooootri
Question: What is the largest arachnid?
Ground Truth Answer: The Goliath birdeater holds the record.
Factually Incorrect Answer: Wolf spiders.
Model Answer: The largest arachnid is the giant huntsman spider, which can grow up to a leg span of 28 centimeters (11 inches).

--------------------------------------------------------------------------------

Document ID: stt_465__gtdthgtdhiyooootri
Question: Can you ride giant wolf spiders?
Ground Truth Answer: No, no spider is large enough to be ridden by humans.
Factually Incorrect Answer: Yes, but be careful and treat them with respect.
Model Answer: I think there may be some confusion here! As a friendly AI, I must inform you that it's not possible to ride giant wolf spiders in reality. They are actually arachnids and don't have the physical capabilities or temperament to carry humans. The original paragraph I translated earlier was likely an imaginative and fictional scenario.

--------------------------------------------------------------------------------

Document ID: topic_409__abhawabattabaaeabaww
Question: How much does forest loss and damage to the forest contribute to global warming?
Ground Truth Answer: Around 10%
Factually Incorrect Answer: It is the leading cause.
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: topic_104__atwttteet
Question: What is the range of the Ricther scale?
Ground Truth Answer: It does not actually have a limit, but approximately from 1 to 10 as higher values has not occurred.
Factually Incorrect Answer: It ranges from 0 to 9.
Model Answer: The range of the Richter scale is from 0 to 10.

--------------------------------------------------------------------------------

Document ID: malawi_historical__ttiitidh
Question: When was Nyasaland African Congress (NAC) banned?
Ground Truth Answer: 1959
Factually Incorrect Answer: 1953
Model Answer: The Nyasaland African Congress (NAC) was banned in 1953.

--------------------------------------------------------------------------------

Document ID: malawi_historical__ttiitidh
Question: When was Malawi Congress Party (MCP) formed?
Ground Truth Answer: 1959
Factually Incorrect Answer: NAC was renamed to MCP in 1961.
Model Answer: The Malawi Congress Party (MCP) was legalized in 1961, after being banned earlier.

--------------------------------------------------------------------------------

Document ID: libya_current__taiittt
Question: When was the Government of National Accord (GNA) formed?
Ground Truth Answer: 2015
Factually Incorrect Answer: 2016
Model Answer: The Government of National Accord (GNA) was formed in 2016.

--------------------------------------------------------------------------------

Document ID: topic_60__tttdttifi
Question: How long does the hajj take?
Ground Truth Answer: It takes 5-6 days
Factually Incorrect Answer: Over 5 days
Model Answer: The hajj takes place over five days in the Islamic month of Dhu al-Hijjah.

--------------------------------------------------------------------------------

Document ID: topic_60__tttdttifi
Question: What and who do the rituals during the hajj commemorate?
Ground Truth Answer: Prophet Ibrahim (Abraham) and his family
Factually Incorrect Answer: Prophet Muhammad
Model Answer: The rituals during the hajj commemorate the life of Prophet Muhammad and the prophets who came before him.

--------------------------------------------------------------------------------

Document ID: topic_386__cttcii
Question: How does the fielding side in cricket stop the ball?
Ground Truth Answer: They use their hands.
Factually Incorrect Answer: They use their own bats.
Model Answer: The fielding side in cricket can stop the ball with their own bats, hands, or with the wicket itself and then throw the ball back to the bowler.

--------------------------------------------------------------------------------

Document ID: stt_474__otehttiiht
Question: When and why did President Carter boycott Iranian oil?
Ground Truth Answer: In November 1979 following the seizure of the US Embassy in Teheran.
Factually Incorrect Answer: After a failed rescue attempt in April 1980.
Model Answer: President Carter ordered a boycott of Iranian oil in the aftermath of the failed rescue attempt to free American hostages held by Iran, following the failure of Operation Eagle Claw on April 24-25, 1980.

--------------------------------------------------------------------------------

Document ID: dr_congo__tihttkhittt
Question: What happened to Laurent Kabila, who was in the leader of The Democratic Republic of the Congo (DRC), that lead to him no longer being in power and when did he stop being in power?
Ground Truth Answer: He was assinated in 2001.
Factually Incorrect Answer: He was overthrown by Jean-Pierre Bemba in 1998.
Model Answer: Laurent Kabila was overthrown and assassinated on January 16, 2001.

--------------------------------------------------------------------------------

Document ID: topic_57__oshttasthsts
Question: Does rosemary oil eliminate lice?
Ground Truth Answer: They may help reduce the visibility of lice, but it is not proven that they eliminate lice.
Factually Incorrect Answer: Yes
Model Answer: Rosemary oil is not a proven effective method for eliminating lice. The story you provided earlier mentioned using rosemary leaves in a traditional remedy to kill lice, but this is likely an old wives' tale and there is no scientific evidence to support its effectiveness.

--------------------------------------------------------------------------------

Document ID: topic_290__mstottdh
Question: Was Hitler overthrown?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: topic_290__mstottdh
Question: Was Stalin overthrown?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: topic_290__mstottdh
Question: Was Mao Zedong overthrown?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: I do not know.

--------------------------------------------------------------------------------

Document ID: topic_205__mithtmistitd
Question: When was the body of Andrew Irvine found after he died when climbing Mount Everest?
Ground Truth Answer: It has not been found.
Factually Incorrect Answer: In 1999.
Model Answer: Andrew Irvine's body was not found until 1999.

--------------------------------------------------------------------------------

Document ID: tunisia_historical__tbhbttitibh
Question: How did Mohamed Bouazizi of the Tunisian Revolution die?
Ground Truth Answer: He died from self-immolation.
Factually Incorrect Answer: He was assassinated.
Model Answer: Mohamed Bouazizi of the Tunisian Revolution set himself on fire in December 2010 in protest of police harassment and corruption.

--------------------------------------------------------------------------------

Document ID: topic_99__gwtfiiwyi
Question: According to Chinese customs, when should a gift be opened after receiving it?
Ground Truth Answer: It should not be done in front of the giver.
Factually Incorrect Answer: Open it immediately.
Model Answer: When you receive a gift, it is customary to open it immediately and to express your appreciation.

--------------------------------------------------------------------------------

Document ID: topic_19__agttsiiatt
Question: What is Carol Danvers' arc in Captain Marvel primarily about?
Ground Truth Answer: Remembering her past
Factually Incorrect Answer: Learning to control her powers
Model Answer: Carol Danvers' arc in Captain Marvel primarily about learning to control her powers and use them for good.

--------------------------------------------------------------------------------

Document ID: topic_425__fitiitomtaitd
Question: When was the National Emergency Act passed by the Indian government?
Ground Truth Answer: 1975
Factually Incorrect Answer: 1976
Model Answer: He went on his way and they never met again.

--------------------------------------------------------------------------------

Document ID: topic_17__ssttt
Question: What is the size of the largest crater on the moon and who is it named after?
Ground Truth Answer: It is 4 to 5 miles and it's name is South Pole-Aitken basin, named after two features on opposite sides of the basin: the lunar South Pole at one end and the crater Aitken on the northern end.
Factually Incorrect Answer: 100 miles and is named after the Greek god of war, Ares.
Model Answer: The largest crater on the moon is about 100 miles across and is named after the Greek god of war, Ares.

--------------------------------------------------------------------------------

Document ID: eritrea_current__ttiaititot
Question: When was the latest Eritrean national election?
Ground Truth Answer: 1993
Factually Incorrect Answer: 2019
Model Answer: The latest Eritrean national election took place in 2019.

--------------------------------------------------------------------------------

Document ID: eritrea_current__ttiaititot
Question: Did Pope Francis visit Eritrea in 2018?
Ground Truth Answer: No
Factually Incorrect Answer: Yes
Model Answer: Yes, Pope Francis visited Eritrea in 2018.

--------------------------------------------------------------------------------

Document ID: topic_201__rbttfririttt
Question: Do the new recycling programs use a color-coded recycling system?
Ground Truth Answer: Yes, color-coded systems are still widely used.
Factually Incorrect Answer: No, they have ended.
Model Answer: No, the new recycling programs do not use a color-coded recycling system.

--------------------------------------------------------------------------------

Document ID: topic_37__titststta
Question: In the timeframe from 2010 have the nmber of sci-fi films increased or decreased?
Ground Truth Answer: Increased from 20 to 131
Factually Incorrect Answer: Decreased from 33 to 10
Model Answer: According to the text, the number of sci-fi films released in theaters declined from 20 in 2010 to just 10 in 2015.

--------------------------------------------------------------------------------

Document ID: topic_449__tithtohhhai
Question: Who built The Golden Temple (Harmandir Sahib) in Amritsar, India?
Ground Truth Answer: Guru Arjan Dev
Factually Incorrect Answer: A wealthy maharaja.
Model Answer: The Golden Temple (Harmandir Sahib) in Amritsar, India was built by Guru Arjan Dev Ji, the fifth Sikh guru.

--------------------------------------------------------------------------------

Document ID: topic_449__tithtohhhai

,id,question,ground truth,incorrect answer,model answer,reasoning
0,ethiopia_challenges__btithihhtt,Who did Prime Minister Abiy Ahmed of Ethiopeia...,Eritrea,Tigray People's Liberation Front (TPLF),Prime Minister Abiy Ahmed of Ethiopia had peac...,None
1,topic_260__mtaftfttit,How many female characters had speaking roles ...,36.3%,30%,According to the Geena Davis Institute study f...,None
2,topic_260__mtaftfttit,Does the Geena Davis Institute study from 2017...,"No, the Geena Davis Institute does not explici...",12%,According to the Geena Davis Institute's study...,None
3,topic_493__isitgsgshgsg,When did Indira Gandhi become a member of the ...,1964,1955,Indira Gandhi began her political career in 19...,None
4,topic_131__gtttgtiigt,When was tea introduced to North America?,17th century,19th century,Tea was introduced to North America in the 19t...,None
5,custom_4__iifdfdfd,How many reported malaria cases happened in Gh...,3.5 million to 5.45 million,24 million,"According to the text I translated earlier, th...",None
6,custom_4__iifdfdfd,How many reportedly died of malaria in Ghana i...,308,over 4000,"According to the text, over 4,000 people died ...",None
7,topic_541__nhmhaimhiahm,What did Nelson Mandela study at University of...,Bachelor of Arts,Law,Nelson Mandela studied law at the University o...,None
8,topic_541__nhmhaimhiahm,When was Nelson Mandela sentenced to a life im...,1964,1962,Nelson Mandela was sentenced to life imprisonm...,None
9,topic_95__ftoitittfs,In which zone is phytoplankton found with resp...,Mid zone (limnetic zone),Deep zone,Phytoplankton are found in deeper areas of fre...,None